import {
  pgTable, uuid, text, timestamp, boolean, integer, index, unique,
} from 'drizzle-orm/pg-core'
import { stores, users } from './tenancy'
import { customers, vehicles } from './customers'
import { appointments, repairOrders, inspections } from './service'
import {
  consentEventTypeEnum, consentScopeEnum, messageChannelEnum,
  messageDirectionEnum, messageStatusEnum,
} from './enums'

/**
 * Service drive communication.
 *
 * TCPA exposure is real: statutory damages run $500–$1,500 per message, per
 * recipient. The defence is documentary, so consent is modelled as an
 * append-only event log and every outbound message records the consent event
 * that authorised it. A boolean column alone proves nothing about what was
 * true at the moment of send.
 */

export const consentEvents = pgTable(
  'consent_events',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id').notNull().references(() => customers.id, { onDelete: 'cascade' }),

    eventType: consentEventTypeEnum('event_type').notNull(),
    scope: consentScopeEnum('scope').notNull(),

    /** The exact address consent applies to — people change numbers. */
    channelAddress: text('channel_address').notNull(),

    /** Where it came from: WRITE_UP, ONLINE_FORM, SMS_REPLY, DMS_IMPORT, VERBAL. */
    source: text('source').notNull(),
    /** Verbatim disclosure the customer agreed to. The heart of the defence. */
    disclosureText: text('disclosure_text'),
    capturedByUserId: uuid('captured_by_user_id').references(() => users.id, { onDelete: 'set null' }),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),

    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('consent_events_customer_idx').on(t.customerId, t.occurredAt),
    index('consent_events_address_idx').on(t.storeId, t.channelAddress),
    index('consent_events_scope_idx').on(t.customerId, t.scope, t.occurredAt),
  ],
)

/** A thread with one customer on one channel. */
export const conversations = pgTable(
  'conversations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    customerId: uuid('customer_id').notNull().references(() => customers.id, { onDelete: 'cascade' }),
    vehicleId: uuid('vehicle_id').references(() => vehicles.id, { onDelete: 'set null' }),

    channel: messageChannelEnum('channel').notNull(),
    /** Customer's address on this channel. */
    customerAddress: text('customer_address').notNull(),
    /** Store's sending number or address. */
    storeAddress: text('store_address'),

    /** Who owns the reply. Unassigned threads are how customers get ignored. */
    assignedUserId: uuid('assigned_user_id').references(() => users.id, { onDelete: 'set null' }),

    isOpen: boolean('is_open').notNull().default(true),
    unreadCount: integer('unread_count').notNull().default(0),
    lastMessageAt: timestamp('last_message_at', { withTimezone: true }),
    lastInboundAt: timestamp('last_inbound_at', { withTimezone: true }),

    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('conversations_unique_thread').on(t.storeId, t.customerId, t.channel, t.customerAddress),
    index('conversations_store_open_idx').on(t.storeId, t.isOpen, t.lastMessageAt),
    index('conversations_assigned_idx').on(t.assignedUserId, t.isOpen),
    index('conversations_customer_idx').on(t.customerId),
  ],
)

export const messages = pgTable(
  'messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    conversationId: uuid('conversation_id').notNull().references(() => conversations.id, { onDelete: 'cascade' }),

    direction: messageDirectionEnum('direction').notNull(),
    channel: messageChannelEnum('channel').notNull(),
    status: messageStatusEnum('status').notNull().default('QUEUED'),

    body: text('body').notNull(),
    subject: text('subject'),
    mediaUrls: text('media_urls'),

    /** Sender for outbound; null for an inbound message from the customer. */
    sentByUserId: uuid('sent_by_user_id').references(() => users.id, { onDelete: 'set null' }),
    /** True when generated by a cadence rule or campaign rather than a person. */
    isAutomated: boolean('is_automated').notNull().default(false),

    /**
     * The consent event that authorised this send. Non-null is enforced in
     * application code for outbound marketing — this column is what you hand a
     * regulator or plaintiff's counsel.
     */
    authorizingConsentEventId: uuid('authorizing_consent_event_id')
      .references(() => consentEvents.id, { onDelete: 'set null' }),
    /** Populated when the send was suppressed, e.g. quiet hours or revoked consent. */
    suppressionReason: text('suppression_reason'),

    // Context, so a thread reads as a service history rather than raw texts.
    appointmentId: uuid('appointment_id').references(() => appointments.id, { onDelete: 'set null' }),
    repairOrderId: uuid('repair_order_id').references(() => repairOrders.id, { onDelete: 'set null' }),
    inspectionId: uuid('inspection_id').references(() => inspections.id, { onDelete: 'set null' }),

    // Provider bookkeeping (Twilio, SendGrid, …).
    providerMessageId: text('provider_message_id'),
    providerError: text('provider_error'),

    queuedAt: timestamp('queued_at', { withTimezone: true }).notNull().defaultNow(),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    deliveredAt: timestamp('delivered_at', { withTimezone: true }),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('messages_conversation_idx').on(t.conversationId, t.createdAt),
    index('messages_store_created_idx').on(t.storeId, t.createdAt),
    index('messages_status_idx').on(t.status),
    index('messages_provider_idx').on(t.providerMessageId),
    index('messages_ro_idx').on(t.repairOrderId),
  ],
)

export const messageTemplates = pgTable(
  'message_templates',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    storeId: uuid('store_id').notNull().references(() => stores.id, { onDelete: 'cascade' }),
    key: text('key').notNull(),
    name: text('name').notNull(),
    channel: messageChannelEnum('channel').notNull(),
    subject: text('subject'),
    /** Mustache-style placeholders: {{customer.firstName}}, {{vehicle.model}}. */
    body: text('body').notNull(),
    /**
     * Marketing templates require marketing consent, not merely transactional.
     * Mislabelling a marketing blast as transactional is the classic TCPA trap.
     */
    isMarketing: boolean('is_marketing').notNull().default(false),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    unique('message_templates_store_key_unique').on(t.storeId, t.key),
    index('message_templates_store_idx').on(t.storeId),
  ],
)
