import type { CadenceTrigger } from '@/lib/cadence'
import type { WorklistItem } from '@/lib/cadence/worklist'

/**
 * Follow-up worklist presentation.
 *
 * Pure and I/O-free. The cadence engine decides what to chase and when; this
 * only decides how a rep reads it. Nothing here re-prioritises or re-schedules
 * a task — two different orders inside one product is how a worklist stops
 * being trusted.
 */

export type FollowUpOwner = 'ADVISOR' | 'BDC' | 'UNASSIGNED'
export type FollowUpUrgency = 'OVERDUE' | 'TODAY' | 'UPCOMING'

export interface FollowUpItem extends WorklistItem {
  /** From the rule that generated it. */
  owner: FollowUpOwner
  smsConsent: boolean
}

export function ownerFrom(role: string | null | undefined): FollowUpOwner {
  if (role === 'ADVISOR') return 'ADVISOR'
  if (role === 'BDC') return 'BDC'
  return 'UNASSIGNED'
}

/** Whole days past due. Negative means still ahead. */
export function overdueDays(dueAt: Date, asOf: Date): number {
  const startOfDue = new Date(dueAt).setHours(0, 0, 0, 0)
  const startOfNow = new Date(asOf).setHours(0, 0, 0, 0)
  return Math.round((startOfNow - startOfDue) / 86_400_000)
}

export function classifyUrgency(dueAt: Date, asOf: Date): FollowUpUrgency {
  const days = overdueDays(dueAt, asOf)
  if (days > 0) return 'OVERDUE'
  if (days === 0) return 'TODAY'
  return 'UPCOMING'
}

// ===========================================================================

export interface TriggerMeta {
  label: string
  glyph: string
  /** One line an advisor can read to know why the task exists. */
  why: string
  /** The four that actually leak money get emphasised in the UI. */
  highValue: boolean
}

const TRIGGER_META: Record<string, TriggerMeta> = {
  DECLINED_SERVICE_FOLLOW_UP: {
    label: 'Declined work',
    glyph: '↩',
    why: 'They said no to work we already quoted. The estimate is still fresh.',
    highValue: true,
  },
  PPM_EXPIRING: {
    label: 'Prepaid expiring',
    glyph: '⌛',
    why: 'Visits they already paid for are about to vanish unused.',
    highValue: true,
  },
  WARRANTY_EXPIRING: {
    label: 'Warranty ending',
    glyph: '§',
    why: 'Factory coverage is running out — the one moment a service contract is easy to justify.',
    highValue: true,
  },
  DORMANT_CUSTOMER: {
    label: 'Win-back',
    glyph: '◌',
    why: 'A customer who used to come in and stopped. Nobody has called them.',
    highValue: true,
  },
  CONTRACT_EXPIRING: {
    label: 'Contract ending',
    glyph: '§',
    why: 'Their service contract is about to lapse.',
    highValue: true,
  },
  POST_VISIT_THANK_YOU: {
    label: 'Post-visit',
    glyph: '☎',
    why: 'Catch a problem before the manufacturer survey does.',
    highValue: false,
  },
  CSI_PRE_EMPTION: {
    label: 'CSI check',
    glyph: '☆',
    why: 'A detractor found now is a detractor you can still fix.',
    highValue: false,
  },
  MAINTENANCE_DUE_MILEAGE: {
    label: 'Maintenance due',
    glyph: '◷',
    why: 'Projected to hit the service interval shortly.',
    highValue: false,
  },
  MAINTENANCE_DUE_TIME: {
    label: 'Maintenance due',
    glyph: '◷',
    why: 'Due by time since the last visit.',
    highValue: false,
  },
  OEM_SCHEDULE_INTERVAL: {
    label: 'Factory schedule',
    glyph: '◷',
    why: 'The manufacturer schedule calls for service around now.',
    highValue: false,
  },
  OPEN_RECALL: {
    label: 'Open recall',
    glyph: '!',
    why: 'An open safety campaign. The manufacturer pays for the work.',
    highValue: true,
  },
  STATE_INSPECTION_DUE: {
    label: 'Inspection due',
    glyph: '✓',
    why: 'State inspection is coming due.',
    highValue: false,
  },
  SEASONAL: { label: 'Seasonal', glyph: '❄', why: 'Seasonal service reminder.', highValue: false },
  MISSED_APPOINTMENT: {
    label: 'Missed appointment',
    glyph: '⊘',
    why: 'They booked and did not arrive. Rebook before they forget.',
    highValue: true,
  },
}

const FALLBACK_META: TriggerMeta = {
  label: 'Follow-up',
  glyph: '•',
  why: 'Generated by a cadence rule.',
  highValue: false,
}

export function triggerMeta(trigger: CadenceTrigger | string): TriggerMeta {
  return TRIGGER_META[trigger] ?? FALLBACK_META
}

// ===========================================================================

export interface FollowUpFilters {
  owner?: FollowUpOwner | 'ALL'
  trigger?: string
  /** Only the four money-leaking types. */
  highValueOnly?: boolean
}

export function filterItems(items: FollowUpItem[], filters: FollowUpFilters): FollowUpItem[] {
  return items.filter((i) => {
    if (filters.owner && filters.owner !== 'ALL' && i.owner !== filters.owner) return false
    if (filters.trigger && i.trigger !== filters.trigger) return false
    if (filters.highValueOnly && !triggerMeta(i.trigger).highValue) return false
    return true
  })
}

export interface FollowUpSection {
  urgency: FollowUpUrgency
  label: string
  items: FollowUpItem[]
}

const SECTION_LABEL: Record<FollowUpUrgency, string> = {
  OVERDUE: 'Overdue',
  TODAY: 'Due today',
  UPCOMING: 'Coming up',
}

/**
 * Split into urgency bands, preserving the engine's ordering inside each.
 *
 * Empty bands are dropped rather than rendered as a heading over nothing — a
 * rep scanning for work should not have to read three headings to find out
 * there are two calls.
 */
export function groupByUrgency(items: FollowUpItem[], asOf: Date): FollowUpSection[] {
  const order: FollowUpUrgency[] = ['OVERDUE', 'TODAY', 'UPCOMING']
  return order
    .map((urgency) => ({
      urgency,
      label: SECTION_LABEL[urgency],
      items: items.filter((i) => classifyUrgency(i.dueAt, asOf) === urgency),
    }))
    .filter((section) => section.items.length > 0)
}

export interface FollowUpSummary {
  count: number
  value: number
  overdueCount: number
  highValueCount: number
  byOwner: { owner: FollowUpOwner; count: number }[]
  byTrigger: { trigger: string; label: string; count: number; value: number }[]
}

export function summarize(items: FollowUpItem[], asOf: Date): FollowUpSummary {
  const byOwnerCount = new Map<FollowUpOwner, number>()
  const byTrigger = new Map<string, { count: number; value: number }>()
  let value = 0
  let overdueCount = 0
  let highValueCount = 0

  for (const item of items) {
    value += item.estimatedValue
    if (classifyUrgency(item.dueAt, asOf) === 'OVERDUE') overdueCount += 1
    if (triggerMeta(item.trigger).highValue) highValueCount += 1

    byOwnerCount.set(item.owner, (byOwnerCount.get(item.owner) ?? 0) + 1)
    const t = byTrigger.get(item.trigger) ?? { count: 0, value: 0 }
    byTrigger.set(item.trigger, { count: t.count + 1, value: t.value + item.estimatedValue })
  }

  return {
    count: items.length,
    value,
    overdueCount,
    highValueCount,
    byOwner: [...byOwnerCount.entries()]
      .map(([owner, count]) => ({ owner, count }))
      .sort((a, b) => b.count - a.count),
    byTrigger: [...byTrigger.entries()]
      .map(([trigger, t]) => ({ trigger, label: triggerMeta(trigger).label, ...t }))
      .sort((a, b) => b.value - a.value || b.count - a.count),
  }
}

// ===========================================================================
// Contact prompts
//
// Prompt only. We compose the message and hand it to the rep; we do not send
// it. A2P 10DLC registration and per-customer consent are prerequisites for
// outbound SMS, and a worklist that quietly texts on a rep's behalf is a TCPA
// exposure measured at $500–1,500 per message.

export function canText(item: FollowUpItem): boolean {
  return item.smsConsent && !item.doNotCall && Boolean(item.customerPhone)
}

export function canCall(item: FollowUpItem): boolean {
  return !item.doNotCall && Boolean(item.customerPhone)
}

/** Why a channel is unavailable, so a rep is never left guessing. */
export function contactBlockedReason(item: FollowUpItem): string | null {
  if (item.doNotCall) return 'Customer asked not to be contacted.'
  if (!item.customerPhone) return 'No phone number on file.'
  if (!item.smsConsent) return 'No SMS consent on file — call instead.'
  return null
}

function firstName(fullName: string): string {
  const first = fullName.trim().split(/\s+/)[0]
  return first && first.length > 1 ? first : fullName
}

/**
 * A text the rep can read, edit and send from their own device.
 *
 * Deliberately short and specific: it names the store, the vehicle and the one
 * reason for the message. Generic blasts are what customers opt out of.
 */
export function buildTextPrompt(item: FollowUpItem, storeName: string): string {
  const who = firstName(item.customerName)
  const vehicle = item.vehicleLabel ? ` on your ${item.vehicleLabel}` : ''

  switch (item.trigger) {
    case 'DECLINED_SERVICE_FOLLOW_UP':
      return `Hi ${who}, it's ${storeName}. Last visit we found work${vehicle} you decided to hold off on. It's still open and I can honour the same price — want me to look at a time this week?`
    case 'PPM_EXPIRING':
      return `Hi ${who}, ${storeName} here. You have prepaid service${vehicle} that expires soon — you've already paid for it. Can I get you booked before it lapses?`
    case 'WARRANTY_EXPIRING':
      return `Hi ${who}, it's ${storeName}. Your factory coverage${vehicle} is close to running out. Worth a quick chat about your options before it does — do you have a few minutes this week?`
    case 'OPEN_RECALL':
      return `Hi ${who}, ${storeName}. There's an open safety recall${vehicle}. The manufacturer covers it at no cost to you — can I book you in?`
    case 'DORMANT_CUSTOMER':
      return `Hi ${who}, it's ${storeName}. We haven't seen you${vehicle} in a while and wanted to check everything is running well. Anything you'd like us to look at?`
    case 'MISSED_APPOINTMENT':
      return `Hi ${who}, ${storeName} here. We missed you at your appointment${vehicle} — no problem at all. Want me to find another time?`
    case 'POST_VISIT_THANK_YOU':
    case 'CSI_PRE_EMPTION':
      return `Hi ${who}, it's ${storeName}. Just checking everything is right${vehicle} after your visit. If anything isn't, tell me and I'll sort it.`
    default:
      return `Hi ${who}, it's ${storeName} about your service${vehicle}. ${item.title}. Is now a good time for a quick call?`
  }
}
